version: '3'
services:
  linkedin.rails.postgres.db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  linkedin.rails.web:
    build: .
    command: bundle exec rails s -p 4001 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "4001:4001"
    depends_on:
      - linkedin.rails.postgres.db
